baseURL = 'http://kyletools.neocities.org/'
title = 'kyletools'
languageCode = 'en-us'
copyright = "2024"
uglyurls = true
relativeURLs = true
paginate = 5
disableKinds = ["sitemap", "RSS", "404", "taxonomy", "term"] 
capitalizeListTitles = false
[params]
Description = "Kyletools is a place for Kyle to roam around and graze freely. Here you can find his thoughts, drawings, and whatever else interests him. Abandon all hope, ye who enter here."
